### ISSUE TITLE
memory leaks of App class

### ISSUE THREAD

**Issue by siilky** [henryiii/CLI11#985]
Using a whole bunch of raw pointers in the App class (here's only a few)
https://github.com/CLIUtils/CLI11/blob/20de8b73bbbabaf2f94dd07c4ece8ff3590af531/include/CLI/App.hpp#L166
https://github.com/CLIUtils/CLI11/blob/20de8b73bbbabaf2f94dd07c4ece8ff3590af531/include/CLI/App.hpp#L202
https://github.com/CLIUtils/CLI11/blob/20de8b73bbbabaf2f94dd07c4ece8ff3590af531/include/CLI/App.hpp#L206
with default empty destructor how is it expected to be managed to avoid memory leaks when running something more complicated than a trivial usage case?

**Comment by levi-de-koning** [comment]
Basically the awnser to this is modern C++ and the convention that raw pointers are not owners of memory
a lot of this data is [non owning](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#p8-dont-leak-any-resources). 

So for example `need_subcommand_` is a non owning list of commands it needs. And since it's non owning it does not leak.

Some example of owning pointers are:
` std::shared_ptr<FormatterBase> formatter_{new Formatter()};`
`std::vector<Option_p> options_{};` where `Option_p` = `using Option_p = std::unique_ptr<Option>;`

**Comment by phlptp** [comment]
we do run a number of memory scans on the code,  if you find an actual memory leak from one of the tools, we would be very interested and look into it quickly.   But like @levi-de-koning  said,  all the pointers you see are non-owning, so have no role in memory management.

**Comment by siilky** [comment]
okay, I was probably misled by CRT reporting, apologizies.
Would you consider using like weak_ptr to make it more explanatory?

**Comment by phlptp** [comment]
That isn't really a good use for weak_ptrs.   I haven't actually encountered that many real use cases for weak ptr honestly.   

I have seen a few use cases for observer_ptr<T> and other similar things when there is a mixed usage and that kind of wrapper makes it clear which is which,   but in the case of CLI11 if it is bare pointer it is non-owning, so is cleanly separated, and clear inside the code.   In user code wrapping them in something else should be perfectly fine.

**Comment by henryiii** [comment]
You would not use a weak pointer for this - you can’t use them for unique pointers, and in order to access the weak pointer, you have to convert it to a shared pointer, so you have to pay a cost for that plus shared pointers have a mutex when accessing. Raw pointers are not in and of themselves bad.
